version: "3.7"
services:
  microproyectos:
    container_name: microproyectos
    image: jesussegura/microproyectos:v1
    build:
      context: .
    ports:
      - "6001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - PORT=6001
    networks:
      - ase-acad
    
  balanceador:
    container_name: balanceador_proyectos
    image: jesussegura/balanceador_proyectos:v1.0
    build:
      context: ./balanceador
    ports:
      - "8082:80"
    networks:
      - ase-acad
networks:
  ase-acad:
